### ISSUE TITLE
add a basic Lotka-Volterra model to the model library

### ISSUE THREAD

**Issue by papsti** [canmod/macpan2#135]
equations [here](https://en.wikipedia.org/wiki/Lotka%E2%80%93Volterra_equations)

using the new model spec on the `refactorcpp` branch

**Comment by davidearn** [comment]
I like the idea of having L-V in the model library, but I have a few suggestions:
- include both L-V predator-prey and L-V competition models
- include the option for a carrying capacity in prey growth (so logistic rather than exponential growth of prey)
- include options for all three standard (Holling) functional responses

Making these options available as part of the model library would not take much extra effort and would potentially draw in a much larger ecological audience.

**Comment by stevencarlislewalker** [comment]
I agree completely @davidearn .  Thank you for these suggestions.

Similarly, listening to Jane's talk last week made me want to include within-host immune response models.

**Comment by papsti** [comment]
i drafted a model definition for the basic lotka-voltera, but i'm running into errors. i'll push a branch off of `refactorcpp` with it so that we can troubleshoot.

**Comment by stevencarlislewalker** [comment]
@jfree-man has completed this task with 8a5d7c10be46208e635aa8abb75be0596f11f84f
