### ISSUE TITLE
Back transformations in `mp_tmb_coef`

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#179]
@bbolker has given us a head start.

https://github.com/canmod/macpan2/blob/47251905c99bec8f8264fb39a673c5616814db34/inst/starter_models/shiver/calibration_example.R#L380-L393

**Comment by stevencarlislewalker** [comment]
@jfree-man , can you please add `backtrans` in `mp_tmb_coef`?

What circumstances will cause it to fail if we just drop it in before the return value?

**Comment by jfree-man** [comment]
> @jfree-man , can you please add `backtrans` in `mp_tmb_coef`?
> 
> What circumstances will cause it to fail if we just drop it in before the return value?

Yes

**Comment by jfree-man** [comment]
@stevencarlislewalker we can drop it in before the return value and it works, provided the transformed parameters are named with preceding "log_" or "logit_". I can add this information to the mp_tmb_coef help doc. It doesn't currently work for transformed distributional parameters because they start with "distr_params", but I can make that change to the regex.

Do we always want to back transform, or do we want it to be optional?

**Comment by stevencarlislewalker** [comment]
Back transformation should be optional.  Yes please add the distr_params (and anything similar).  Please all all of this to the doc.

Thank you!
