### ISSUE TITLE
New function: triplets_to_matrix

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#9]
New function called `triplets_to_matrix(x, v, m)` with the following arguments.
* `x` -- A matrix
* `v` -- A column vector of values to add to elements of x
* `m` -- A matrix of integers

Here is pseudo-code for the function.
```
# 1. Fill x with all zeros.
x[,] = 0

# 2. Add elements in v to elements of x, according to the indices in m.
for (int k=0; i<n; i++)
  x[m[k,0], m[k,1]] += v[m[k,2], 0]

# 3. Return x.
x
```

**Comment by guanwg** [comment]
Lets weight both the (known or unknown) pros and cons of using sparse matrices. The only benefit I can see is that a sparse matrix saves space. Since most of the matrices used in MacPan are fairly small, the benefit is not so significant. The computations that involves sparse matrices are slower in general, especially when operating with dense matrices. 

The unknown cons are (1) not sure if matrix operations between sparse and dense matrices will generate sparse or dense matrix; (2) Some of our defined functions may fail because I assume they are dense matrices.

**Comment by bbolker** [comment]
The main use case where it *might* make sense to use a sparse matrix is in log-linear modeling, where the matrices will be medium-sized and potentially sparse.  In principle sparse matrix multiplication can be *faster* because we can skip any position that is a structural zero in either argument. 

I don't know what the performance implications would be for (say) multiplying a 200 x 20 sparse matrix by a 20-vector; I could do some quick R benchmarks ...

**Comment by stevencarlislewalker** [comment]
This sounds reasonable.  Thanks Weiguang.  It would probably be good to chat tomorrow as well to make sure that we understand each other.

**Comment by guanwg** [comment]
I have meeting 10-11am tomorrow. We can meet either before 10am or after 11am.

**Comment by guanwg** [comment]
@bbolker I've done a timing test of matrix multiplication. I used both dense and sparse matrices in the test. The size of these matrices is (2000x2000) with 2500 non-zero elements. They results are
```
Using matmul for dense matrices
time used: 1308679
Using reglar * matrix multiplication operator for dense matrices
time used: 1271597
Using reglar * matrix multiplication operator for sparse matrices
time used: 3501
Using reglar * matrix multiplication operator for dense and sparse matrices
time used: 14791

```
So, you are right --- It's much faster to matrix operations using sparse matrices if the matrix is indeed very sparse.

**Comment by guanwg** [comment]
oh the timing unit is microseconds.

**Comment by stevencarlislewalker** [comment]
Might not need this given #18 and the `groupSums` function.

**Comment by stevencarlislewalker** [comment]
We have `groupSums` and `assign` that cover all of this.
