### ISSUE TITLE
explain/document last-step difference between macpan2 and deSolve

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#96]
When comparing macpan2 with equivalent `deSolve::ode(..., method = "euler")` output the last step differs slightly (more than numerical fuzz).  I know this came up earlier and was explained, but I don't remember the explanation.  Could it be documented somewhere?

As an example, install the latest `macpan2helpers` version and

```r
example("compare_fits")
compare_fits(macpan2_results, deSolve_results, drop_last = FALSE)
```

**Comment by stevencarlislewalker** [comment]
This is because of two things.

1. by default the state of the matrices produced by expressions evaluated _before_ the simulation loop are returned as the output for time-step `0`
2. by default the state of the matrices produced by expressions evaluated _after_ the simulation loop are returned as the output for time-step `time_steps+1`

The default to the `model$report` method is `model$report(.phases = c("before", "during", "after")`. If you would only like to return the state of the matrices produced by expressions evaluated at each step of the simulation loop, one should use `model$report(.phases = "during")`. 

I'm beginning to think that the default should actually be `model$report(.phases = "during")`.

**Comment by stevencarlislewalker** [comment]
This is done with `mp_trajectory`
